### ISSUE TITLE
i18n cache + translation missing + rails validations -> Can't dump...

### ISSUE THREAD

**Issue by the8472** [svenfuchs/i18n#150]
Rails' `ActiveModel::Errors#generate_message` includes the value of a field in the i18n options. The value of a field can contain things that can't be marshaled, e.g. files (using paperclip) or hashes with procs (custom attr-accessors) or entire sets of objects (validating a relation).

Normally that's not a problem since those options don't get cached. But if the translation is missing then a `MissingTranslation` Exception is built and the options are included and then passed to the i18n cache. Since most caches use `ActiveSupport::Cache::Store` they get get marshaled which ultimately leads to an Exception since they can't be marshaled.

`MissingTranslation::Base` already attempts to catch some of these:

``` ruby
options.each { |k, v| self.options[k] = v.inspect if v.is_a?(Proc) }
```

But this doesn't cover the case where arbitrary, non-marshalable objects might occur in the options.

One solution would be to `.inspect`  the whole options hash when building the exceptions. But that might possibly break someone's except-handling logic.

**Comment by gr8bit** [comment]
We also stumbled across this problem with I18n::Backend::Cache due to ActiveRecord validations putting the validated object in the options (key ":object"), the I18n backend passing the option into I18n::MissingTranslation's options and the redis cache store finally not being able to marshal it to store it and failing.
```
TypeError: can't dump hash with default proc
```
In our case this error was caused by a User object, which we definitely did not want to appear in the translation cache. What we did was to clean all the options that are reserved keys from the MissingTranslation's options hash. To stay compatible, we copied the MissingTranslation object and removed the reserved keys (I18n::RESERVED_KEYS). All these changes were applied to the file
```
i18n/backend/cache.rb
```
only.
This is the patch, put this into your config/initializers/i18n.rb (or what suits you best). I hope it may help someone.
```ruby
module I18n
  module Backend
    module Cache

      protected

      def _fetch(cache_key, &block)
        result = I18n.cache_store.read(cache_key) and return result
        result = catch(:exception, &block)

        # HOTFIX CHANGES START
        # options hash might contain interpolations as well as i18n options
        # (see I18n::RESERVED_KEYS), some of which contain objects that cannot
        # be marshal'ed (e.g. some ActiveRecord-objects). This causes
        # the redis cache store to fail during marshal'ling. To fix it, we
        # remove all the reserved option keys from the MissingTranslation
        # object's options by creating a new object which is then written to
        # the store. To maintain compatibility the original, unmodified
        # MissingTranslation-object is returned.
        cache_result = result
        if result.is_a?(MissingTranslation)
          cache_result = I18n::MissingTranslation.new result.locale, result.key, result.options.except(*I18n::RESERVED_KEYS)
        end
        # HOTFIX CHANGES END

        I18n.cache_store.write(cache_key, cache_result) unless cache_result.is_a?(Proc)
        result
      end

    end
  end
end

**Comment by radar** [comment]
I am unable to reproduce this issue on i18n 0.7.0.

If you're still able to reproduce this issue, please provide me with an app which does so.

Thanks!

**Comment by MartinKoerner** [comment]
@radar I can reproduce this with i18n 0.7.0 and 0.8.1
I added a small generated Rails 5.0.2 project with sqlite3 under Ruby 2.3.1
[i18n_bug_reproduce.zip](https://github.com/svenfuchs/i18n/files/947083/i18n_bug_reproduce.zip)
It has a chain with SimpleBackend and ActiveRecord backend.
The tests are configured to use caching. If you start memcached prior to the test run, it will succeed, but you'll see an error in the logs.

The reason is, that I made the Room model un-serializable, using a stored lambda (this example is a bit constructed, but it might happen). 
Another way (happened in a real-life project) is the usage of a gem like deferred_associations, which has side effects, too (I debugged into it, but I did not find the root cause, why the associations are not serializable though).


What is the reason behind trying to cache translations exceptions in I18n::Backend::Cache#_fetch? Wouldn't it be sufficient to cache `nil` instead and handle this?

**Comment by tappleby** [comment]
Running into this issue as well. In my case the result is a MissingTranslation error w/ an active record model in `options[:value]`

> What is the reason behind trying to cache translations exceptions in I18n::Backend::Cache#_fetch? Wouldn't it be sufficient to cache nil instead and handle this?

I would have expected this use case to happen. Or one of:
- Invalidate cache entry for this failing key.
- Ignore and keep the previous translation around.

**Comment by tappleby** [comment]
We didnt need to store the MissingTranslation error in the cache for our app, worked around the issue at the cache store layer:

```ruby
class I18nDelegatedCacheStore < DelegateClass(ActiveSupport::Cache::Store)
  def write(name, value, options = nil)
    value = nil if value.is_a? I18n::MissingTranslation
    super(name, value, options)
  end
end

I18n.cache_store = I18nDelegatedCacheStore.new(I18n.cache_store)
```

**Comment by jefvlamings** [comment]
@tappleby You solution fits great for our application.

**Comment by pduey** [comment]
In my case, on v1.8.2, the issue was limited to my test env with:

    TypeError: singleton can't be dumped

I'm using rspec. I mock a (unrelated) method on an object, which gets a validation error with a custom message. I18n tries to cache the missing translation with the invalid object attached as an option. However, in rspec, mocking a method adds a singleton method, which fails on Marshal.dump

I can't think of a case where it's necessary, or even desirable, to include the object that triggered the missing translation in the cache. And it could mean that sensitive information is being written to the cache in cleartext. Could this even be a security issue, e.g., if memcached is hacked?

So borrowing from the previous solutions:

    module I18n
      class MissingTranslation
        # Note: the object that caused the missing translation might fail marshaling when attempting to write to cache.
        # It seems like a bad idea to include that in the cached value anyway.
        def initialize(*args)
          super
          options.delete :object
        end
      end
    end
