### ISSUE TITLE
What's the value of extending a new module inside `I18n`?

### ISSUE THREAD

**Issue by PikachuEXE** [svenfuchs/i18n#313]
Refer to https://github.com/svenfuchs/i18n/blob/master/lib/i18n.rb#L15

Just curious

**Comment by carlosantoniodasilva** [comment]
If we look at the commit that introduced the `extend Module.new` pattern, it won't tell us anything: c5d9e8cfbda9bdac0dd4f4231d12e5eb8a1c184e. However, if we go up one commit, we end up in: e02d87b5821d117de3583defec460213c18855cb, which is a merge of #111, and that should give us some insight on why there's a module being extended vs just defining the methods there - so that you can extend I18n and call super.

That's all I know :)
