### ISSUE TITLE
I18n.t(nil) returns "translation missing: de.no key"

### ISSUE THREAD

**Issue by rafaelfranca** [svenfuchs/i18n#329]
_From @eiked on November 9, 2015 4:31_

I came here because of the other bug, aka I18n.t("")

But while looking at it, I'm not even sure if I18n.t(nil) does the right thing.
1) I might want to argue that translating nil should return nil
2) others might argue that I18n.t() should always return a String Object

I believe I18n.t(nil) should be changed to return nil.
because that is the only sensible answer if you try to translate nothing.
(don't complaint, don't raise, just simply return nil)

This might also help when localizing applications,
because nil would traverse through th localization layer
without no further effort.

I18n.translate(nil)
=> "translation missing: de.no key"

looks like a bad choice.
because I really can imagine a reason to translate nil.
(but in oaccassions you really want to this: I18n.t(foo || "nil")

but as it currently stands, nil is lost in translation,
and this is a lot more trouble.

This change will break software that relies on I18n.t(nil) to return a string.
but then I18n.t("") raises.

_Copied from original issue: rails/rails#22228_

**Comment by rafaelfranca** [comment]
_From @eiked on November 9, 2015 5:24_

Let's discuss what how default should be handled with a nil argument

I suggest tthat I18n.t(nil) should always return nil,
even on I18n.t(nil, default:foo)
because nil is really a special case that should not be catched by the default:
I believe that would really make it more predictable.

I might to suggest another paramter for the nil case,
that would be:
I18n.t(foo, default:'key missing', nil:'Oops I'm NIL')

while some people might oppose to use the nil: as a keyword argument ...

but I believe this is completely legal within the ruby syntax, and it looks nice
(because :nil != nil)

**Comment by radar** [comment]
Hey @eiked,

Thanks for writing in about this. I agree that `I18n.t(nil)` should indeed return nil. But I do not agree with this:

> I suggest that `I18n.t(nil)` should always return nil even on `I18n.t(nil, default:foo)`

I think that if someone is passing in a dynamic value as the first argument where that value _could_ be `nil`, then the `default` value should be respected. To not respect that would special-case `I18n.t`'s `default` behaviour, with this special rule of "if the first arg is nil, ALWAYS return nil, even if a default is specified". This is a violation of the Principle of Least Surprise, and would be the only reason I disagree with this.

If you'd like to submit a PR to make it so that `I18n.t(nil)` returns `nil`, while `I18n.t(nil, default: "foo")` returns "foo", then that would be most welcome.

Thanks!
